#!/usr/bin/env python3
"""
Quick setup script for Free Crypto LLM Bot
Helps configure the .env file with your Discord token
"""
import os
from pathlib import Path

def setup_env():
    """Setup .env file with Discord token"""
    bot_dir = Path(__file__).parent
    env_file = bot_dir / '.env'
    env_example = bot_dir / 'env.example'

    print("🔧 Free Crypto LLM Bot Setup")
    print("=" * 50)

    # Check if .env already exists
    if env_file.exists():
        print(f"⚠️  .env file already exists at: {env_file}")
        response = input("Do you want to overwrite it? (y/N): ").strip().lower()
        if response != 'y':
            print("❌ Setup cancelled. Existing .env file preserved.")
            return

    # Get Discord token
    print("\n📝 Enter your Discord bot token:")
    print("   (You can paste it here - it will be saved securely)")
    discord_token = input("Discord Token: ").strip()

    if not discord_token:
        print("❌ Discord token is required!")
        return

    # Optional: Get other API keys
    print("\n🔑 Optional API Keys (press Enter to skip):")

    etherscan_key = input("Etherscan API Key (optional): ").strip()
    coingecko_key = input("CoinGecko API Key (optional): ").strip()

    # Ollama configuration
    print("\n🤖 Ollama Configuration:")
    ollama_url = input("Ollama URL [http://localhost:11434]: ").strip() or "http://localhost:11434"
    ollama_model = input("Ollama Model [mistral]: ").strip() or "mistral"

    # Create .env file
    env_content = f"""# Discord Bot Configuration
# Generated by setup script
DISCORD_TOKEN={discord_token}

# Ollama LLM Configuration
OLLAMA_URL={ollama_url}
OLLAMA_MODEL={ollama_model}

# Etherscan API (Free Tier)
# Get your free API key from: https://etherscan.io/apis
ETHERSCAN_API_KEY={etherscan_key if etherscan_key else 'your_etherscan_api_key_here'}

# CoinGecko API (Optional - Free Tier)
# Get your free API key from: https://www.coingecko.com/en/api
COINGECKO_API_KEY={coingecko_key if coingecko_key else 'your_coingecko_api_key_here'}

# Solana RPC (Optional)
SOLANA_RPC_URL=https://api.mainnet-beta.solana.com
"""

    try:
        with open(env_file, 'w') as f:
            f.write(env_content)

        print(f"\n✅ .env file created successfully at: {env_file}")
        print("\n🔒 Security Note:")
        print("   - The .env file contains sensitive tokens")
        print("   - Make sure .env is in your .gitignore")
        print("   - Never commit .env to version control!")

        # Check .gitignore
        gitignore = bot_dir.parent / '.gitignore'
        if gitignore.exists():
            with open(gitignore, 'r') as f:
                if '.env' in f.read():
                    print("   ✅ .env is already in .gitignore")
                else:
                    print("   ⚠️  Consider adding .env to .gitignore")
        else:
            print("   ⚠️  No .gitignore found - consider creating one")

        print("\n🚀 Next steps:")
        print("   1. Make sure Ollama is running: ollama serve")
        print("   2. Pull a model: ollama pull mistral")
        print("   3. Run the bot: python run_free_crypto_llm_bot.py")
        print("   4. Invite bot to server using the OAuth2 URL")

    except Exception as e:
        print(f"❌ Error creating .env file: {e}")

if __name__ == "__main__":
    setup_env()



